version: "2"

services:
  php:
    environment:
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_ENABLED: 1
      PHP_XDEBUG_REMOTE_ENABLE: 1
      PHP_XDEBUG_REMOTE_AUTOSTART: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      PHP_XDEBUG_REMOTE_IDEKEY: "IDEKEY"
      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"
      PHP_XDEBUG_REMOTE_PORT: "9000"
    volumes:
      - ~/.ssh:/root/.ssh
      - ./:/var/www/html

  nginx:
    volumes:
      - ./:/var/www/html:cached