<?php

/**
 * @file
 * Contains demo_umami_general.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function demo_umami_general_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the demo_umami_general module.
    case 'help.page.demo_umami_general':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function demo_umami_general_theme() {
  return [
    'demo_umami_general' => [
      'render element' => 'children',
    ],
  ];
}
